gacha/Controllers/chartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using gacha.Models;
using gacha.DTO;

namespace gacha.Controllers
{
    public class chartController : Controller
    {
        private readonly gachaContext _context;

        public chartController(gachaContext context)
        {
            _context = context;
        }
        // GET: chart/Index
        public async Task<IActionResult> Index()
        {
            //性別圓餅圖
            ViewBag.boy = _context.userInfo.Where(b => b.gender == "男").Count();
            ViewBag.girl = _context.userInfo.Where(b => b.gender == "女").Count();

            // 獲取當前時間
            ViewBag.CurrentTime = DateTime.Now.ToString("yyyy-MM-dd HH:mm");
            return View();
        }


        //追蹤清單長條圖
        //GET:chart/machineData
        [HttpGet]
        public async Task<IEnumerable<machineData_DTO>> machineData(int id)
        {
            var machineTrackingData = await (from t in _context.trackingList
                                             join g in _context.gachaMachine
                                             on t.gachaMachineId equals g.id
                                             join gt in _context.gachaTheme
                                             on g.themeId equals gt.id
                                             where gt.id == id
                                             group t by new { t.gachaMachineId, g.machineName } into groupedData
                                             select new machineData_DTO
                                             {
                                                 MachineId = groupedData.Key.gachaMachineId,
                                                 MachineName = groupedData.Key.machineName,
                                                 TrackCount = groupedData.Count()
                                             }).ToListAsync();
            return machineTrackingData;
        }

        //追蹤清單長條圖 全部主題分類
        //GET:chart/getThemeName
        [HttpGet]
        public async Task<IEnumerable<gachaTheme_DTO>> getThemeName()
        {
            var gachaTheme = await _context.gachaTheme.Select(t => new gachaTheme_DTO
            {
                id = t.id,
                themeName = t.themeName,
            }).ToListAsync();

            return gachaTheme;
        }

        //追蹤清單長條圖 各主題分類
        //GET:chart/getThemeNamebyId
        [HttpGet]
        public async Task<IEnumerable<gachaTheme_DTO>> getThemeNamebyId(int id)
        {
            var gachaTheme = await _context.gachaTheme.Where(s => s.id == id).Select(t => new gachaTheme_DTO
            {
                id = t.id,
                themeName = t.themeName,
            }).ToListAsync();

            return gachaTheme;
        }

        //儲值月份折線圖
        //GET:chart/GetMonthlyRevenue
        [HttpGet]
        public async Task<IEnumerable<monthlyRevenue_DTO>> GetMonthlyRevenue(int year)
        {
            var monthlyRevenue = from r in _context.rechargeList
                                 where r.rechargeDate.HasValue && r.rechargeDate.Value.Year == year
                                 group r by new { r.rechargeDate.Value.Month } into grouped
                                 select new monthlyRevenue_DTO
                                 {
                                     Month = grouped.Key.Month,
                                     TotalAmount = grouped.Sum(r => r.amount)
                                 };

            return await monthlyRevenue.OrderBy(mr => mr.Month).ToListAsync();
        }

    }
}

gacha/Views/chart/Create.cshtml
@model gacha.Models.userInfo

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>userInfo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="userName" class="control-label"></label>
                <input asp-for="userName" class="form-control" />
                <span asp-validation-for="userName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="phoneNumber" class="control-label"></label>
                <input asp-for="phoneNumber" class="form-control" />
                <span asp-validation-for="phoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="address" class="control-label"></label>
                <input asp-for="address" class="form-control" />
                <span asp-validation-for="address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="gender" class="control-label"></label>
                <input asp-for="gender" class="form-control" />
                <span asp-validation-for="gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="emailToken" class="control-label"></label>
                <input asp-for="emailToken" class="form-control" />
                <span asp-validation-for="emailToken" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="points" class="control-label"></label>
                <input asp-for="points" class="form-control" />
                <span asp-validation-for="points" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

gacha/Views/chart/Delete.cshtml
@model gacha.Models.userInfo

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>userInfo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.userName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.userName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.phoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.phoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.emailConfirm)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.emailConfirm)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.emailToken)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.emailToken)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.points)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.points)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

gacha/Views/chart/Details.cshtml
@model gacha.Models.userInfo

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>userInfo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.userName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.userName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.phoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.phoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.emailConfirm)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.emailConfirm)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.emailToken)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.emailToken)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.points)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.points)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

gacha/Views/chart/Edit.cshtml
@model gacha.Models.userInfo

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>userInfo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="userName" class="control-label"></label>
                <input asp-for="userName" class="form-control" />
                <span asp-validation-for="userName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="phoneNumber" class="control-label"></label>
                <input asp-for="phoneNumber" class="form-control" />
                <span asp-validation-for="phoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="address" class="control-label"></label>
                <input asp-for="address" class="form-control" />
                <span asp-validation-for="address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="gender" class="control-label"></label>
                <input asp-for="gender" class="form-control" />
                <span asp-validation-for="gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="emailConfirm" class="control-label"></label>
                <input asp-for="emailConfirm" class="form-control" />
                <span asp-validation-for="emailConfirm" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="emailToken" class="control-label"></label>
                <input asp-for="emailToken" class="form-control" />
                <span asp-validation-for="emailToken" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="points" class="control-label"></label>
                <input asp-for="points" class="form-control" />
                <span asp-validation-for="points" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

gacha/Views/chart/Index.cshtml
@using System.Web
@{
    ViewData["Title"] = "";
}
@section Styles {
    <style>
        .card-header {
            text-align: center;
            font-size: 20px;
        }
    </style>
}
@* <div class="row">
    <div class="col-3 my-3">
        <select id="themeSelect" class="form-select col-3" aria-label="Default select example">
            <option disabled>主題</option>
        </select>

    </div>
</div> *@
<div class="row">

    <div class="col-lg-8">
        <div class="card mb-4">
            <div class="card-header">
                <div class="row">
                    <div class="col-4">
                        <select id="themeSelect" class="form-select col-3" aria-label="Default select example" style="  background-color: rgba(255, 205, 86,0.2);">
                            <option disabled>主題</option>
                        </select>
                    </div>
                    <div class="col-3">
                        <i class="fa-solid fa-gamepad fa-xl" style="color: #daae10;"></i>
                        熱門機台分析
                    </div>
                </div>
            </div>
            <div class="card-body"><canvas id="tracking" width="100" height="50"></canvas></div>
            <div class="card-footer small text-muted">上次更新時間 : @ViewBag.CurrentTime</div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="card mb-4">
            <div class="card-header">
                <i class="fa-solid fa-venus-mars fa-xl" style="color: #daae10;"></i>
                會員性別分析
            </div>
            <div class="card-body">
                <canvas id="myPieChart" width="100" height="50"></canvas>
            </div>
            <div class="card-footer small text-muted">上次更新時間 : @ViewBag.CurrentTime</div>
        </div>
    </div>
</div>


<!-- 儲值月份分析 -->
<div class="row">
    <div class="col-lg-12">
        <div class="card mb-4">
            <div class="card-header">
                <i class="fa-solid fa-dollar-sign fa-lg" style="color: #daae10;"></i>
                營業額分析
            </div>
            <div class="card-body"><canvas id="recharging" style="width:200px;height:100px"></canvas></div>
            <div class="card-footer small text-muted">上次更新時間 : @ViewBag.CurrentTime</div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-annotation@latest"></script>


    <script>
        var trackingChart; // 全局變數來保存圖表實例
        var rechargeChart; // 全局變數來保存圖表實例


        //追蹤機台長條圖
        $(document).ready(function () {
            updateGender(); //性別圓餅圖
            getThemeName();
            updateTracking(1);
            rechargeLine([2021, 2022, 2023]); //傳遞多個年份來同時顯示它們的營業額數據

        })
        function updateGender() {
            //性別圓餅圖
            const ctx = document.getElementById('myPieChart').getContext('2d');
            const genderData = {
                labels: [
                    '男',
                    '女',
                ],
                datasets: [{
                    label: '註冊人數',
                    data: [@ViewBag.boy, @ViewBag.girl],
                    backgroundColor: [
                        'rgb(54, 162, 235)',
                        'rgb(255, 99, 132)',

                    ],
                    hoverOffset: 4
                }]
            };
            new Chart(ctx, {
                type: 'pie',
                data: genderData
            });
        }
        function updateTracking(themeId) {
            $.ajax({
                type: "GET",
                url: `https://localhost:7273/chart/machineData?id=${themeId}`,
            }).done(data => {
                // console.log(data)
                if (trackingChart) {
                    trackingChart.destroy();
                }
                const labels = [];
                const datasetData = [];
                data.forEach(item => {
                    // console.log(item.machineName);
                    // console.log(item.trackCount);
                    labels.push(item.machineName);  // 添加機器名稱到 labels
                    datasetData.push(item.trackCount);  // 添加追蹤數量到 datasetData
                });

                const tracking = document.getElementById('tracking').getContext('2d');
                const trackingData = {
                    labels: labels,
                    datasets: [{
                        label: '追蹤數量',
                        data: datasetData,
                        backgroundColor: [
                            'rgba(255, 99, 132, 0.2)',
                            'rgba(255, 159, 64, 0.2)',
                            'rgba(255, 205, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(201, 203, 207, 0.2)'
                        ],
                        borderColor: [
                            'rgb(255, 99, 132)',
                            'rgb(255, 159, 64)',
                            'rgb(255, 205, 86)',
                            'rgb(75, 192, 192)',
                            'rgb(54, 162, 235)',
                            'rgb(153, 102, 255)',
                            'rgb(201, 203, 207)'
                        ],
                        borderWidth: 1
                    }]
                };

                const config = {
                    type: 'bar',
                    data: trackingData,
                    options: {
                        scales: {
                            y: {
                                beginAtZero: true,
                                ticks: {
                                    // forces step size to be 50 units
                                    stepSize: 1 // 設定刻度步長為1，確保以整數顯示
                                },
                            },
                        }
                    },
                };
                trackingChart = new Chart(tracking, config);
            }).fail(err => {
                alert(err.responseText);
            });
        };
        function getThemeName() {

            var trackCount
            $.ajax({
                type: "GET",
                url: `@Url.Action("getThemeName", "chart")`,
            }).done(data => {
                var themes = data;
                const selectElement = document.getElementById('themeSelect');
                // console.log(data);
                themes.forEach(theme => {
                    const option = document.createElement('option');
                    option.value = theme.id;
                    option.textContent = theme.themeName;
                    selectElement.appendChild(option);
                });
            }).fail(err => {
                alert(err);
            });
        }
        function rechargeLine(years) {
            console.log('Years:', years); // 調試輸出 years 的值
            const rechargeCanvas = document.getElementById('recharging').getContext('2d');
            const month = ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'];
            const predefinedColors = ['#FF6384', '#36A2EB', '#FFCE56'];

            // 用來儲存每個年份的數據，鍵是年份，值是對應的數據
            const yearDataMap = {};
            let ajaxCalls = [];

            years.forEach((year, index) => {
                ajaxCalls.push(
                    $.ajax({
                        type: "GET",
                        url: `https://localhost:7273/chart/GetMonthlyRevenue?year=${year}`,
                    }).done(data => {
                        try {
                            const datasetData = [];
                            let totalAmount = 0; // 用來儲存每年的總營業額
                            data.forEach(item => {

                                const amount = item.totalAmount;
                                datasetData.push(amount);
                                totalAmount += amount; // 累加總營業額
                            });

                            // 格式化總營業額，添加千位分隔符
                            const formattedTotalAmount = totalAmount.toLocaleString();

                            // 根據年份將數據儲存到 yearDataMap 中
                            yearDataMap[year] = {
                                label: `${year} 營業額: ${formattedTotalAmount}`,
                                data: datasetData,
                                fill: false,
                                borderColor: predefinedColors[index % predefinedColors.length],
                                tension: 0.1
                            };
                        }
                        catch 
                        {
                            console.error(`Error processing data for year ${year}:`, error);
                        }
                        
                    }).fail(err => {
                        console.log(`Error fetching data for year ${year}:`, err);
                    })
                );
            });

            // 等待所有 AJAX 請求完成後，依據 years 的順序來填充 datasets
            $.when.apply($, ajaxCalls).done(() => {
                if (rechargeChart) {
                    rechargeChart.destroy();
                }

                const datasets = years.map(year => yearDataMap[year]); // 按照 years 的順序生成 datasets

                const rechargeData = {
                    labels: month,
                    datasets: datasets
                };

                const config = {
                    type: 'line',
                    data: rechargeData,
                    options: {
                        plugins: {
                            legend: {
                                labels: {
                                    font: {
                                        size: 16 // 增大圖例標籤的字體大小
                                    }
                                }
                            },
                            tooltip: {
                                bodyFont: {
                                    size: 14 // 增大工具提示的字體大小
                                },
                                titleFont: {
                                    size: 16 // 增大工具提示標題的字體大小
                                }
                            }
                        },
                        scales: {
                            x: {
                                ticks: {
                                    font: {
                                        size: 14 // 增大 x 軸標籤的字體大小
                                    }
                                }
                            },
                            y: {
                                ticks: {
                                    font: {
                                        size: 14 // 增大 y 軸標籤的字體大小
                                    }
                                }
                            }
                        }
                    }
                };



                rechargeChart = new Chart(rechargeCanvas, config);
            });
        }



        $('#themeSelect').on('change', function () {
            var selectedValue = $(this).val(); // 取得選中的值
            console.log(selectedValue)
            updateTracking(selectedValue);     // 傳遞選中的值給 updateTracking 函數
        })
    </script>
}